version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    labels:
      - "Type: Dependencies"
      - "Status: Review Needed"
      - "Priority: Low"
